### ISSUE TITLE
Typescript can't identify type due to @types is in devDependencies

### ISSUE THREAD

**Issue by Yesterday17** [dlau/koa-body#100]
## Promblem/Feature Request Summary
Typescript cannot find declaration file (.d.ts) of formidable since `@types/formidable` is in devDependencies and it wouldn't be installed when using `npm install`.

## Environment Information

  * koa-body: 4.0.3
  * Koa: 2.5.1
  * Node.js: v8.11.1

## Current Behavior
Typescript cannot find declaration file (.d.ts) of formidable.

## Steps to Reproduce
1. Clone this [repository](https://github.com/Yesterday17/sample-statistics).
2. Run `npm install`
3. Run `npm run test`

## Expected Behavior
It should work.

## Possible Solution
Move `@types/koa": "^2.0.39` to dependencies.

## Context (Environment)
Sorry, I pressed the enter button by accident. It's been edited now.

**Comment by Yesterday17** [comment]
@MarkHerhold hmmm, It has no problem because i want it to be used and added `@types` myself.

But in fact, if you don't add `@types` in dependencies, that's to say, if you have a thousand `@types` used, then the user has to add another 1k packages which is used by the package at a higher layer. I think it's not acceptable.

And it's the only package which i have to add `@types` myself though it's not used in my own program. :cry:

**Comment by MarkHerhold** [comment]
Published 4.0.4. Thanks for explaining the situation.
