### ISSUE TITLE
tsc failed

### ISSUE THREAD

**Issue by Sorosliu1029** [dlau/koa-body#104]
## Promblem/Feature Request Summary

tsc failed with error: 

> Property `body` is optional in type `Request` but required in type `BaseRequest`

## Environment Information

  * koa-body:  4.0.4
  * Koa:  2.5.1
  * Node.js:  8.11.1

## Current Behavior

typescript compile failed

## Expected Behavior

Pass tsc period

## Possible Solution

change https://github.com/dlau/koa-body/blob/857c51cffdca245c097665cb01f138be18460bcd/index.d.ts#L6 to `body: any`

or just remove this line

**Comment by MarkHerhold** [comment]
Thanks for the report! What version of `tsc` are you on?

**Comment by Sorosliu1029** [comment]
@MarkHerhold `tsc` with version `2.9.1`

**Comment by MarkHerhold** [comment]
@Sorosliu1029 any update?
