### ISSUE TITLE
onEnd doesn't work

### ISSUE THREAD

**Issue by Melonxx** [dlau/koa-body#116]
![image](https://user-images.githubusercontent.com/30221824/46590348-2dd42700-cae5-11e8-8047-e5d3029f312e.png)

why onEnd doesn't work

**Comment by chardlau** [comment]
onEnd is not support here

**Comment by MarkHerhold** [comment]
It looks like you are trying to pass `onEnd` to `formidable` which doesn't exist (?).

I don't think `koa-body` supports handling `onEnd` so I'm not sure how to help you with this.
