### ISSUE TITLE
Example not correct with respect to multipart fields

### ISSUE THREAD

**Issue by kevinludwig** [dlau/koa-body#117]
In koa-body@4, the behavior of multipart has changed. The only example that exists for setting this up is here:

https://github.com/dlau/koa-body/blob/master/examples/multipart.js. 

The only example showing how to access fields is a `console.log` (line 40) which is not correct (it indicates that fields is in `ctx.request.fields`, and in prior versions they were in `ctx.request.body.fields`). I ended up cracking open the source code of `koa-body` to figure out where fields are actually at (e.g. `ctx.request.body` _is_ the fields). Simply updating the example would be a huge help so that it's not misleading.

**Comment by damianb** [comment]
This should have been addressed in #138.
