### ISSUE TITLE
Type incompatibility with koa-bodyparser

### ISSUE THREAD

**Issue by edevil** [dlau/koa-body#118]
## Problem/Feature Request Summary

In my project I make use of apollo-graphql-koa, which brings with it koa-bodyparser. In other views of my project which are not graphql related I use koa-body, since it includes support for multipart requests. However, when using TypeScript the type definitions of the two packages are incompatible.

## Current Behavior

```
> tsc -p tsconfig.build.json

node_modules/@types/koa-bodyparser/index.d.ts:21:9 - error TS2687: All declarations of 'body' must have identical modifiers.

21         body: {} | null | undefined;
           ~~~~

node_modules/@types/koa-bodyparser/index.d.ts:21:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'any', but here has type '{}'.

21         body: {} | null | undefined;
           ~~~~

node_modules/koa-body/index.d.ts:6:9 - error TS2687: All declarations of 'body' must have identical modifiers.

6         body?: any;
          ~~~~
```

## Steps to Reproduce

1. Include koa-bodyparser (+types) and koa-body
1. Try to compile

## Expected Behavior

Program should compile successfully.

## Possible Solution

Change the type definition to match koa-bodypaser's since it is more strict.

**Comment by dearsaturn** [comment]
Any luck on this? :|

**Comment by Himself65** [comment]
I have the same problem

**Comment by MarkHerhold** [comment]
I hate to say this but I don't know of a good solution here. Perhaps migrating to `koa-bodyparser` is actually the most advantageous... 🤔

**Comment by MarkHerhold** [comment]
Please see the comment thread in #119 - koa-bodyparser changed their type definitions so this should not be an issue any longer.
