### ISSUE TITLE
when i use DELETE and it wouldn't get anything so i remove DELETE an it work

### ISSUE THREAD

**Issue by ckken** [dlau/koa-body#12]
if (["GET", "HEAD", "DELETE"].indexOf(this.method.toUpperCase()) === -1) {

**Comment by dlau** [comment]
Hi, yes, recently we disallowed `GET`, `HEAD`, and `DELETE` requests.

In retrospect, this might be too restrictive.

I have a PR up here #13 to conditionally disable this check. It would involve setting `{strict: false}` in your options.

I'll merge tomorrow if there are no objections.

**Comment by dlau** [comment]
see #13 , instantiate the module with `{strict: false}`

**Comment by ckken** [comment]
get it thanks
