### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by rightaway** [dlau/koa-body#121]
I see the breaking changes in the readme, but having a proper changelog for each release even minor ones would help us determine when and if to upgrade. Otherwise it feels risky not knowing what was changed and time consuming to have to go through every git commit to check.

**Comment by MarkHerhold** [comment]
I agree. If you want to take the first pass at this, I would appreciate it.

**Comment by MarkHerhold** [comment]
Fixed in a6a4a29a9049d754f12d453a501b76ff1425b880
