### ISSUE TITLE
[possible] bug in example

### ISSUE THREAD

**Issue by lx-931203** [dlau/koa-body#123]
One example from this repo has reference
```
ctx.request.fields
```
that is `undefined` practically.

Is it broken, outdated?

**Comment by MarkHerhold** [comment]
To my knowledge, it's neither broken or outdated. The example code is present to show that the field is `undefined` because other parts of the library populate that field but doing a file upload does not.

Added a comment in 13872b0c1680bd80fb86a3fb6b85be3ca4d54906
