### ISSUE TITLE
Cannot find module './unparsed.js'

### ISSUE THREAD

**Issue by mattschoch** [dlau/koa-body#127]
## Problem/Feature Request Summary
v4.0.5 adds an import for `require('./unparsed.js');` but `./unparsed.js` is not in the build.

This gives a `Error: Cannot find module './unparsed.js'` error.

## Environment Information

  * koa-body: 4.0.5
  * Koa: ^2.5.0
  * Node.js: 8+

**Comment by MarkHerhold** [comment]
Fixed in 4.0.6 via https://github.com/dlau/koa-body/pull/126.

Very sorry about that guys.
