### ISSUE TITLE
Unexpected error when option.includeUnparsed is set and request body is empty

### ISSUE THREAD

**Issue by SilentAntenna** [dlau/koa-body#129]
## Environment Information

  * koa-body: 4.0.6
  * Koa: 2.6.2
  * Node.js: 10.14.2

## Current Behavior

If options.includeUnparsed is set, line 106/119 in index.js will always be executed:

`ctx.request.body[symbolUnparsed] = body.raw;`

which may trigger an exception when the request doesn't have a body and `ctx.request.body[symbolUnparsed]` is undefined.

## Possible Solution

fix line 105/118 like this:

`if (body.parsed && ! ctx.is('text')) {`

**Comment by MarkHerhold** [comment]
Thanks for the report and sorry you hit an issue.

@zevisert, could you weigh in on this?

**Comment by zevisert** [comment]
Spot on report - I saw the title and realized right away it was that line, my bad. I guess I was going under the assumption that `co-body` was returning an empty object rather than `undefined`. I'll shoot you a PR later today.

**Comment by MarkHerhold** [comment]
Much appreciated @zevisert !

**Comment by SilentAntenna** [comment]
Many thanks.
I forgot to close this issue, sorry.
