### ISSUE TITLE
file uploading doesn't work on serverless lambda

### ISSUE THREAD

**Issue by webdev522** [dlau/koa-body#132]
## Problem/Feature Request Summary
I'm using [serverless](https://serverless.com) with Koa

## Environment Information

  * koa-body: 4.0.8
  * Koa: 2.7.0
  * Node.js: 8.10.0

## Current Behavior
It works on my local machine, but It doesn't work on lambda when I use koa-body
It always returns 502 bad gateway error.

This issue is from serverless or from koa-body?

**Comment by MarkHerhold** [comment]
Is there a stack trace you can provide that relates to the 502 error?

It sounds like it would be an issue with Serverless/AWS API Gateway if your project is running correctly locally.

**Comment by webdev522** [comment]
Thanks for your quick reply.

when I run my project with serverless-offline locally, it causes error

I'm using babel and it makes this error if I add `import koaBody from 'koa-body';` on my index.js file

{
"errorMessage": "Error while loading api",
"errorType": "TypeError",
"stackTrace": [ "TypeError: require is not a function",...
}

Actually I posted the same issue on severless repo, too.
And will check further on my end.

Regards.

**Comment by MarkHerhold** [comment]
Do you use Babel during local development too?

**Comment by MarkHerhold** [comment]
Closing until there is a response.
