### ISSUE TITLE
koa-body should not blacklist body parsing on DELETE requests

### ISSUE THREAD

**Issue by damianb** [dlau/koa-body#133]
koa-body should not blacklist DELETE method for body parsing.  

Per [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) and the HTTP 1.1 specification, it is permitted to send a body with a DELETE request.  In order to enable parsing of request bodies for DELETE methods, we have to wholesale disable strict mode, which means we're parsing it for GET and HEAD too - *this is not a good solution*.

**Comment by damianb** [comment]
Working on a PR which enables more granular selection of which methods body parsing should be used.

This will also result in a compatibility shim for strict mode, allowing its continued use, but would effectively deprecate it.

**Comment by doums** [comment]
I'm agree with you, it's just annoying that we can't use the body's request when using an http DELETE request..
