### ISSUE TITLE
Should we by default disallow bodies on GET requests?

### ISSUE THREAD

**Issue by dlau** [dlau/koa-body#14]
Thinking about this, some articles have cropped up recently:

https://blogs.dropbox.com/developers/2015/03/limitations-of-the-get-method-in-http/

Is it a good idea to be permissive by default?

**Comment by tunnckoCore** [comment]
Yep. I think it should be. In times where REST principle is the king...
There's no logic for me to have body in GET requests or in other words - changing the state with GET requests, for this we have POST. So.. yea, disallow by default.

ASAP I'll commit these changes to the koa-better-body. I already open an issues there and this is in my todo list.

**Comment by ivan-kleshnin** [comment]
> There's no logic for me to have body in GET requests or in other words - changing the state with GET requests, for this we have POST. So.. yea, disallow by default.

Body in GET does not imply changing state by itself.
How do you propose to overcome URL length limitations with GET ?
