### ISSUE TITLE
How to limit file size - multipart/form-data

### ISSUE THREAD

**Issue by alexaleluia12** [dlau/koa-body#140]
## Problem/Feature Request Summary
Limit file size using multipart/form-data
Related issue: 
https://github.com/dlau/koa-body/issues/66
https://github.com/dlau/koa-body/issues/23

## Environment Information

  * koa-body: 4.1.0
  * Koa: 2.7.0
  * Node.js: 10.15.0

## Current Behavior
Allow send file bigger than `formLimit` option.
Is this a bug ? If i can send a body bigger than defined value.  Is this propertie affect the body only in certain conditions ?

## Steps to Reproduce
```sh
git clone https://github.com/alexaleluia12/koa-upload.git
npm i
npm run start
```
send a txt file bigger than 1k, using multipart/form-data, pass the file through `file` field

## Expected Behavior
Throw an error

## Context (Environment)
I want to send a file to server.

**Comment by damianb** [comment]
Looks like it's only for urlencoded forms.

Perhaps something for 5.0.0 (ding #139) where we hook up formLimit up to formidible's `maxFieldsSize` property and then better document how one can limit the actual *file* upload size limit (which is actually formidible's `maxFileSize` option.

Would def be a BC breaker though.

**Comment by MarkHerhold** [comment]
`koa-body` users `formidable` to perform file parsing so the option needs to be passed to `formidable`. I think this behavior is understandably confusing and should probably be addressed in a later release (ref #139).

A few other notes about your sample code:
* I recommend removing the error handler
* Math.random() isn't cryptographically secure, just FYI

I would change the options in your code to:
```js
app.use(koaBody({
    multipart: true,
    json: true,
    formLimit: MAX_BODY,
    textLimit: MAX_BODY,
    formidable: {
        maxFileSize: MAX_BODY
    }
}));
```

**Comment by MarkHerhold** [comment]
@damianb ha! you beat me by seconds 😆

**Comment by damianb** [comment]
Hah.

Anyways, I do think we ought to directly expose our own upload limit property (proxied to formidible's `maxFileSize`) for something a little easier to work with.
