### ISSUE TITLE
upload docx named -\.docx parsed wrong

### ISSUE THREAD

**Issue by GeaGo** [dlau/koa-body#146]
## Problem/Feature Request Summary
I upload a doc file named -\.docx, I got a file with no extension

## Environment Information

  * koa-body: 4.0.6
  * Koa: 2.5.3
  * Node.js: 10.15.2

## Current Behavior
the file on server with no extension and ctx.request.file.name is '.docx'

## Steps to Reproduce
1. upload a docx named -\.docx

**Comment by damianb** [comment]
Sample code is seriously needed here - because as far as I can tell, this is more likely to be a problem with `formidable` than `koa-body`.

**Comment by GeaGo** [comment]
yes, you're right. I close this issue
