### ISSUE TITLE
Can I get body data from GET request?

### ISSUE THREAD

**Issue by doanthai** [dlau/koa-body#153]
## Problem/Feature Request Summary

I need get body data from GET request
## Environment Information

  * koa-body: 4.1.0
  * Koa: 2.7.0
  * Node.js: 10.15.3

## Current Behavior

I can't get body data from GET request. I don't really know koa supported that or from koa-body library.
## Steps to Reproduce
1. I call GET request from postman with body is raw json and header has Content-Type is application/json.
2. In node server, I show 3 variables is ctx.body, ctx.requests.body and ctx and all of them don't have or containt any data in body request
## Expected Behavior

I can get body data from GET request
## Possible Solution

Change data from body to param and make get request become post request in server.
But that will change every my client code.

**Comment by damianb** [comment]
Are you disabling strict mode, or adding `GET` to the `parsedMethods` array?  `GET` is not body-parsed by default.

Reference the [options](https://github.com/dlau/koa-body#options) in the readme.
