### ISSUE TITLE
Can the directory be created automatically according to uploadDir

### ISSUE THREAD

**Issue by chenguzhen87** [dlau/koa-body#167]
Error: ENOENT: no such file or directory, open 'e:\upload\upload_0404d3c61c592a006b9bed12a2d0f5bd.png'
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

**Comment by MarkHerhold** [comment]
You control the upload directory with the `uploadDir` option. `uploadDir` is passed to formidable. I recommend creating the folder yourself. We're trying to keep `koa-body` fairly minimal.

Please see https://github.com/node-formidable/formidable#options
