### ISSUE TITLE
Example with koa-router doesn't work

### ISSUE THREAD

**Issue by maturano** [dlau/koa-body#18]
The [code example](https://github.com/dlau/koa-body#usage-with-koa-router) using koa-router doesn't works neither the files `koa-router.js` and `multipart.js` in the `examples` directory. All generates the error below:
 ```
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: app.use() requires a generator function
```

---

Screenshot:
![2015-08-24-221441_605x292_scrot](https://cloud.githubusercontent.com/assets/5768813/9457896/949b83a4-4aad-11e5-8077-7f262d57686f.png)

**Comment by dlau** [comment]
Great catch, the `package.json` is set to `koa-router` version `*`

Recent change broke the `app.method` function patching functionality, see:
https://github.com/alexmingoia/koa-router/blob/master/history.md#500
```
Remove confusing API for extending koa app with router methods. Router#use() does not have the same behavior as app#use().
```

I'll update the example

**Comment by dlau** [comment]
ref https://github.com/dlau/koa-body/commit/2fd93126c13755df3da3f3b78ca0fc8db540ddd4

Pls grab the latest copy and try again, close issue if it works!

**Comment by maturano** [comment]
It works! :+1:

**Comment by ansenhuang** [comment]
I am looking for the method to solve this problem, it is too covert so that I spent lots of time. I never think the latest version has itself problem, but it works now. Thank you!
