### ISSUE TITLE
Set filename on multipart upload

### ISSUE THREAD

**Issue by pensierinmusica** [dlau/koa-body#20]
Hi,

I'm trying to figure out how to set the filename of an incoming multipart upload. I'd prefer to avoid renaming the file afterwards.

Formidable docs mention this:

- https://github.com/felixge/node-formidable#formidablefile
- https://github.com/felixge/node-formidable#filebegin

Is there any way to access `form` and the `fileBegin` event using `koa-body`?

Thanks!

**Comment by dlau** [comment]
Hi,

There isn't a good way to do this internally right now. You might want to just set up `formidable` yourself and hook into that `fileBegin` event.

More extensibly, we could also take in generic functions that get called on specific content types. The signature may look something like this:

```js
var formidable = require('formidable');

app
  .use(koaBody({
    multipart: true,
    formLimit: 15,
    onMultiPart: function (ctx, opts, done) {
      var form = new formidable.IncomingForm(opts);
      ...
      done(null, {fields: {}, files: {}});
    }
  }))
```

any thoughts?

**Comment by pensierinmusica** [comment]
Hi, this is what the `formidable` team suggests: https://github.com/felixge/node-formidable/issues/361#issuecomment-162520070

What do you think? Cheers!

**Comment by dlau** [comment]
Thanks for following up w/ the formidable guys, how about something like this then?

https://github.com/dlau/koa-body/commit/7870e6cd92d77688cb33f66f5f430c86f7516f62

usage would look something like:

```js
    app.use(koaBody({
      multipart: true,
      formidable: {
        uploadDir: __dirname + '/temp',
        onFileBegin: function(name, file) {
          ...
        }
      }
    }));

```

I also looked really quick at exposing more `on*` hooks, but none of them really made much sense. What do you think?

**Comment by pensierinmusica** [comment]
Looks awesome  :) If this is going to be pushed soon to Npm let me know, as I'll include the updated version straight away in my code! Cheers

**Comment by dlau** [comment]
published in npm as v1.4.0

Thanks!

**Comment by pensierinmusica** [comment]
@dlau, just checked, still looks 1.3.0 in npm... any idea?  :)

**Comment by dlau** [comment]
Published again! Sorry about that. It went to a private npm repo

**Comment by pensierinmusica** [comment]
No worries  ;) Thx!
