### ISSUE TITLE
Limit max size for files upload

### ISSUE THREAD

**Issue by pensierinmusica** [dlau/koa-body#23]
Hi! There should really be a way to limit the max size for files upload.

In my understanding, this is relates to https://github.com/felixge/node-formidable/issues/324#issuecomment-164272686.

Any thoughts? Cheers!

**Comment by pensierinmusica** [comment]
After reading all the issue here: https://github.com/felixge/node-formidable/issues/324

And this thread on SO: http://stackoverflow.com/questions/20553575/how-to-cancel-user-upload-in-formidable-node-js

Does this mean the only way to get this solved is to switch the entire `koa-body` library to use [`multer`](https://github.com/expressjs/multer) instead of [`formidable`](https://github.com/felixge/node-formidable)?

**Comment by tunnckoCore** [comment]
Hi there!
This package support passing any of the formidable options through `options.formidable`. I don't think this "issue" is related to this package.
