### ISSUE TITLE
automatically create the uploadDir folder

### ISSUE THREAD

**Issue by fflrichard** [dlau/koa-body#27]
it will throw an error if the uploaddir folder does not exist, although i just need to write one line, i think it's more convenient that koabody can automatically create the uploadDir folder. would you please add the code?

**Comment by leo** [comment]
@fflrichard This property isn't related to `koa-body`. You should close this issue and add it to [formidable](https://github.com/felixge/node-formidable).

**Comment by tunnckoCore** [comment]
It's not a job that they should do. And it's normal to fail.
