### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by MQZhangThu** [dlau/koa-body#29]
Is there any way to handle the Error. For example, if I set the uploadDir as a path which doesn't exist, the app will crash.

**Comment by dlau** [comment]
Hi,

The easiest way would be to wrap this middleware with another middleware.

On a train atm, rough pseudocode -- in koa 1.x flavor (I havent had a chance to look at v2 promise syntax yet):

```js
var opts = {};
var koaBody = require('koa-body')(opts);
var wrapper = function *(next) {
  try {
    koaBody(next);
  }
  catch (e) {
    // handle
  }
}
```
