### ISSUE TITLE
Doc issue?

### ISSUE THREAD

**Issue by weching** [dlau/koa-body#32]
In the section "Some options for formidable" of documentation, it indicates:

> maxFields {Integer} Limits the number of fields that the querystring parser will decode, default 10
> maxFieldsSize {Integer} Limits the amount of memory a field (not file) can allocate in bytes, default 2mb

For "maxFields", it's 1000 in formidable.
For "maxFieldsSize", here you indicated the amount of **a field**, but actually it is the amount of all form fields.

**Comment by dlau** [comment]
Thanks!

Ref 06be712dec09c01d1cd2cfe77b2e89fc25a02f84

  this.maxFields = opts.maxFields || 1000;
  this.maxFieldsSize = opts.maxFieldsSize || 2 * 1024 * 1024;


https://github.com/felixge/node-formidable/blob/53bdc35c5f63502566cbb982587c3b9a44e1d2b4/lib/incoming_form.js#L26
