### ISSUE TITLE
Multipart array

### ISSUE THREAD

**Issue by pimpreneil** [dlau/koa-body#34]
When sending an array in a simple urlencoded POST, it gets converted into an object or an array of objects thanks to the `qs` lib used by the `co-body` lib.

Example:

``` bash
 books[new-1][is_new]=1
 books[new-1][title]=test
```

Becomes:

``` js
 {
     "books": {
         "new-1": {
             "is_new": "1",
             "title":"test"
         }
     }
 }
```

But when the same field is sent in a multipart POST (e.g. with a picture). Then the `formidable` lib is used, and because this lib only processes the fields independantly, it doesn't do the conversion and we end up having the following:

``` js
 {
     "books[new-1][is_new]":"1",
     "books[new-1][title]":"test"
 }
```

A simple fix I have found is to ask `qs` to rebuild a query string and reparse it instantly like so:

``` js
qs.parse(qs.stringify(body.fields))
```

It probably is not the best solution but it does the job

**Comment by dlau** [comment]
Thanks, will look at this over the weekend.

**Comment by knife-s** [comment]
any update on this?
