### ISSUE TITLE
Get raw stream from koa-body when upload with multipart/form

### ISSUE THREAD

**Issue by gogorush** [dlau/koa-body#36]
I checked the docs and can't find any way of accessing the raw stream. In node-formidable module, there is a onPart function by which you can add an listener. But seems it doesn't work with this module.

**Comment by tunnckoCore** [comment]
Yea, i think it's not possible. But http://npm.im/koa-better-body is more flexible than any other body parser and working with formidable too. Can pass formidable instance to control the events and such things, and more. :)

**Comment by gogorush** [comment]
@tunnckoCore thx, gonna check out koa-better-body module.
