### ISSUE TITLE
this.request.body returns empty object

### ISSUE THREAD

**Issue by marcelorl** [dlau/koa-body#39]
I've tried a really quick test with koa-router example you provided and `this.request.body` returns empty object.

**Comment by BruceHem** [comment]
Do you have koa bodyparser?

On Sep 21, 2016 7:04 AM, "Marcelo rizzardo lima" <notifications@github.com>
wrote:
>
> I've tried a really quick test with koa-router example you provided and
this.request.body returns null

**Comment by tunnckoCore** [comment]
@BruceHem, what you mean by that?! That's the idea of `koa-body` - it is bodyparser.

@marcelorl, you may be very interested in `koa-better-body` which is older than that, more stable and freakin configurable. Its latest v3 is awesome for me :)

**Comment by BruceHem** [comment]
@tunnckoCore sorry my bad i confused though this was koa.
