### ISSUE TITLE
Question: How can I keep a multipart file in memory?

### ISSUE THREAD

**Issue by jcalfee** [dlau/koa-body#40]
I need to parse many requests with images and forward them to another server.  Is there a way to avoid writing each one to a file?  I would rather access some sort of Buffer with the file's data in it.  Here is an example request:

>curl -F "image=@$HOME/Pictures/blue_red_pill.jpg" -F "username=slim" http://localhost:3234/uploadImage

**Comment by tunnckoCore** [comment]
It sounds more like `formidable` question. I'm not very familiar, but can't do much from such packages. If you find some workaround around event listeners you can use `koa-better-body` than and pass IncomingForm instance to its options.

**Comment by jcalfee** [comment]
thank you

**Comment by Ajaxy** [comment]
@jcalfee did you find a solution for that?
