### ISSUE TITLE
Support plans for koa v2 ?

### ISSUE THREAD

**Issue by rgranger** [dlau/koa-body#44]
Just opening this issue to track when this module will support koa v2.

**Comment by dlau** [comment]
Please see

https://github.com/dlau/koa-body/tree/koa2

published in npm under `next` tag

`npm install koa-body@2`

Will maintain the default as koa v1 support until koa bumps to v2

**Comment by andreyrd** [comment]
koa latest is now at v2, can this be made latest now?
