### ISSUE TITLE
can i use koa-body to analysis xml ?

### ISSUE THREAD

**Issue by wuchuguang** [dlau/koa-body#50]
koa-body support post xml analysis?

**Comment by dlau** [comment]
No, this library does not parse xml.

**Comment by fritx** [comment]
But why the ctx.body is still `{}` (json) when `content-type: 'text/xml'`?

**Comment by fritx** [comment]
@Thyiad I wanted to use koa-body to parse wechat xml 😆

**Comment by Thyiad** [comment]
@fritx node-tenpay did parse work. We need not to do parse anymore. I just modify the koa-body to parse xml as text.Then it work well!

**Comment by zzswang** [comment]
> @fritx node-tenpay did parse work. We need not to do parse anymore. I just modify the koa-body to parse xml as text.Then it work well!

@Thyiad how to modify koa-body to parse xml as text ?

**Comment by Thyiad** [comment]
@zzswang 我是直接把源码拷贝过去修改的，把xml当成txt处理。
另外，你试过了没，如果直接用会有问题吗？我当时是看了下源码，直觉觉得不支持，到node-pay的时候会有问题，加上支付调试麻烦，所以没去尝试，直接就改掉自用了。

**Comment by zzswang** [comment]
@Thyiad 不能直接用的。我已经换成 koa-bodyparser 了

**Comment by Thyiad** [comment]
@zzswang 但是koa-body同时还支持上传文件，改里面代码就一行

**Comment by zzswang** [comment]
发个 pr 吧，解决一下 :)
