### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by hhtu** [dlau/koa-body#54]
Hi

there is a typo in README at **Some options for formidable** section

maxFieldsSize {Integer} Limits the amount of memory all fields together (except files) can allocate in bytes. If this value is exceeded, an 'error' event is emitted, default 2mb (2 * 2 * 1024)

It seems the last part should be

2mb (2 * 1024 * 1024)

**Comment by dlau** [comment]
Thanks https://github.com/dlau/koa-body/commit/190972da91f4bd24d649795e7892d1e625347cd1
