### ISSUE TITLE
typescript declaration files

### ISSUE THREAD

**Issue by naxmefy** [dlau/koa-body#56]
could you create some?

**Comment by dlau** [comment]
Hi, yes typescript bindings would definitely be useful.

I'm a bit crushed with work at the moment-- I'll get to this when I have a chance. In the meantime feel free to submit a pr.

**Comment by weicracker** [comment]
https://github.com/weicracker/-types-koa-body
 
this is my using

**Comment by naxmefy** [comment]
@weicracker on https://github.com/weicracker/-types-koa-body/blob/master/index.d.ts#L41 you wrote **onerror** but it seems to be **onError**. Is this a problem? 

@dlau I will add a PR for this issue

**Comment by andyblaesus** [comment]
@dlau  @naxmefy How's the ts definition PR going through? I see the PR is a month-old now. Is there something I can help with?

**Comment by naxmefy** [comment]
@andyblaesus i dont know - @dlau have to merge it if he wants it

**Comment by dlau** [comment]
Sorry for the delay, merging!

**Comment by dlau** [comment]
Live in `2.4.0`

**Comment by andyblaesus** [comment]
@dlau Hmm, when I `npm install koa-body`, I don't get the `index.d.ts`. I did get the `2.4.0` version though. Am I doing something wrong? Thanks!

**Comment by andyblaesus** [comment]
Never mind, it seems to work now. Thanks you for the efforts!
