### ISSUE TITLE
Where can I handle error when file size exceeds maxFieldsSize? 

### ISSUE THREAD

**Issue by awayisblue** [dlau/koa-body#61]
I  set koa-body options to 
```js
{
    formidable:{
        uploadDir: './static/uploads',
        keepExtensions:true,
        maxFieldsSize :1024*1024,  //1M
    },

    multipart: true,
    urlencoded: true,
}
```
when I upload a file with size larger than 1M, I get a 0 size file in my disk, but koa-body do not throw this error. How I can handle it ?

**Comment by FleyX** [comment]
![image](https://user-images.githubusercontent.com/29558551/34372990-822f1aa6-eb13-11e7-8baa-771ff30cca71.png)
maxFieldsSize can't limit the size of upload file

**Comment by xergiodf** [comment]
@awayisblue you should use `maxFileSize: 1 * 1024 * 1024`
