### ISSUE TITLE
can't generate the folder for the upload files automaticly

### ISSUE THREAD

**Issue by percy507** [dlau/koa-body#62]
@dlau 

Hi, thanks for your awesome koa2 middleware. It is really powerful.

Now i have an advice for `upload files`.

> **when user specify a folder for the upload files, generate the specified folder automatically if the folder not existed**

---

```js
app.use(koaBody({
    multipart: true,
    formidable: {
        uploadDir: './uploads',
        keepExtensions: true,
        onFileBegin: function(name, file) {
            file.path = 'uploads/' + file.name
        }
    }
}))
```

```bash
➜  koa2-test node "/Users/percy/working/koa2-test/app.js"
server at http://localhost:3333 ~
请求: GET /
请求: POST /page/upload
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'uploads/'
```

If i do not create the folder manually, i will get the error message as shown above.

**Comment by dlau** [comment]
In the interest of keeping this module as simple as possible, this is up to the user

**Comment by wtto00** [comment]
@percy507 

I got the same error message, but I don't know why. After I searched for a long time, finally I found this issue. Thanks a lot!
