### ISSUE TITLE
Is there a way to limit uploaded file size?

### ISSUE THREAD

**Issue by zdila** [dlau/koa-body#66]
https://github.com/felixge/node-formidable/issues/324

**Comment by dlau** [comment]
Looks like there is an undocumented max file size option you can pass into formidable

https://github.com/felixge/node-formidable/blob/05e4743078f0a10cc556ec7351a629643e2b95b9/lib/incoming_form.js#L28

Use the `options.formidable` object to pass this
https://github.com/dlau/koa-body#options

**Comment by cirias** [comment]
But the `maxFileSize` is not in the `index.d.ts` of `koa-body`
