### ISSUE TITLE
Causes 'Not Found'

### ISSUE THREAD

**Issue by MicroDroid** [dlau/koa-body#67]
Whenever I add `koaBody` as a middleware, no matter what order, koa returns `Not Found` all the time

**Comment by dlau** [comment]
Can you post a code sample please?

Thanks

**Comment by MicroDroid** [comment]
```
// router.js

...

const koaBody = require('koa-body');

const AuthController = require('./controllers/auth');

router.post('/login', koaBody, AuthController.login);

// controllers/auth.js

module.exports = {
	login: async function (ctx, next)  {
		console.log(ctx.request.body);
		
		ctx.body = {
			foo: 1,
		};

		await next();
	},
}
```

**Comment by MicroDroid** [comment]
I figured it out, it is `koaBody()` not `koaBody`

I will PR this https://github.com/dlau/koa-body#usage-with-koa-router

**Comment by dlau** [comment]
Was just gonna comment, glad you figured it out! 

Indeed the docs are wrong, looking forward to the pr.
