### ISSUE TITLE
Create new NPM release

### ISSUE THREAD

**Issue by JarvisPrestidge** [dlau/koa-body#69]
I'd love to use this package with the recent type definition files you've added without having to add them manual. 

Please update the NPM package :slightly_smiling_face:

**Comment by JarvisPrestidge** [comment]
Sorry, my mistake you have recently published. Still though, the type definition files aren't making it through for some reason.

**Comment by JarvisPrestidge** [comment]
I've created a PR to fix this #71

**Comment by dlau** [comment]
In `v2.5.0`
