### ISSUE TITLE
type check before uploading?

### ISSUE THREAD

**Issue by DennisJames** [dlau/koa-body#79]
I wander if I can check the file's type before uploading it to the disk. So that I can interrupt the job with the wrong type of file.
For example, formidable expose `IncomingForm.prototype.onPart` to users so that we can define our own function to handle it.
```
form.onPart = function(part){
  if(part.mime.indexOf('image') != -1){
    this._error(new Error('wrong file type'));
  } else {
    this.handlePart(part); // default work of formidable
  }
}
```

**Comment by damianb** [comment]
You should keep in mind that mimetypes are not entirely reliable, especially for user-provided data and that you need to fully validate the user supplied file against the given mimetype; many browsers will perform MIME sniffing unless explicitly ordered not to, and will ignore provided content-types and go with their own.  Obviously, this isn't a good idea with user-supplied data.

**Comment by MarkHerhold** [comment]
Closing this as validation is not going to be a part of koa-body.
The proper approach would probably be to allow all content to be uploaded and then validate the entire payload.
