### ISSUE TITLE
how can i rename the upload file?

### ISSUE THREAD

**Issue by monokeroslun** [dlau/koa-body#8]

**Comment by tunnckoCore** [comment]
Actually its your option how you save and rename the file. Response have `res.body.files` object like
```js
{
"size": 748831,
"path": "/tmp/f7777b4269bf6e64518f96248537c0ab.png",
"name": "some-image.png",
"type": "image/png",
"mtime": "2014-06-17T11:08:52.816Z"
}
```
from here you have path and should use it to move/copy and rename the file where you want.

It isnt something koa-body (koa at all) and node specific, its always save the files to tmp. PHP also does this thing.

**Comment by dlau** [comment]
Short answer, you have to rename the file yourself. (thanks @tunnckoCore ) you wrote a response while I was typing! :+1: 

First instantiate the middleware with `multipart: true`
```js
var body = require('koa-body')
app.use(body({patchNode:true, patchKoa:true, multipart: true}));
```

In your route handler, let's say you POST a file named `image`.

You will get a `this.request.body` object with a `files` key.

```js
var route = function *(){
  var file = this.request.body.files.image;

  yield thunkify(fs.rename)(file.path, path.join(__dirname, './public/uploads/', file.name));

  this.status = 200;
  this.body = '/uploads/' + filename;
};
```

See [node-formidable Formidable.file](https://github.com/felixge/node-formidable#formidablefile)

**Comment by tunnckoCore** [comment]
haha, yea :)
Good clarification!

**Comment by tunnckoCore** [comment]
But its not needed to patch both koa and node :)
