### ISSUE TITLE
form-data not supper object ??

### ISSUE THREAD

**Issue by exvu** [dlau/koa-body#81]
today,I found a issue when using form-data，this middleware not parse object like 
<img width="1089" alt="qq20180315-132319 2x" src="https://user-images.githubusercontent.com/25115931/37445655-1e3acf3a-2854-11e8-8461-850d99c929f1.png">
i found cource code
<img width="516" alt="qq20180315-133527 2x" src="https://user-images.githubusercontent.com/25115931/37445975-bf14b15e-2855-11e8-8d97-479692f6c0d0.png">

Seems to only support

Excuse me, my English is poor.

**Comment by danmin25** [comment]
I guest you should convert object to string like `{id:2, name:Tom}` => `"id=2&name=Tom"` or not use Content-Type: application/x-www-form-urlencoded but application/json

**Comment by MarkHerhold** [comment]
@xuan45 is correct. As far as I know form data is always a flat structure. If you wish to inflate the data into a nested JSON object, you will have to do this yourself or just use JSON.
