### ISSUE TITLE
supertest devDependency generating security warning

### ISSUE THREAD

**Issue by damianb** [dlau/koa-body#84]
Upon installation, npm is generating this warning:

```
$ npm i
npm WARN notice [SECURITY] superagent has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=superagent&version=2.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

Details: https://nodesecurity.io/advisories?search=superagent&version=2.3.0

ED: Appears to be a sub-dep of supertest, so not as critical of an issue.

**Comment by MarkHerhold** [comment]
Fixed in 952deb64638240934952e0c63811b92de44babaf which will go into the next release
