### ISSUE TITLE
v1.6.0 deps co-body version 

### ISSUE THREAD

**Issue by vladimirdh** [dlau/koa-body#85]
The deps version of co-body now is *,  and just hours ago co-body release a new version(6.0.0), our Node server(6.10) down because of syntax error, so I think to lock the version.

**Comment by Yann-Wang** [comment]
+1

**Comment by anaik-zam** [comment]
+1

**Comment by yandongxu** [comment]
@dlau update npm package, plz

**Comment by LealLee** [comment]
+1

**Comment by dlau** [comment]
Live in `2.6.0`

**Comment by yandongxu** [comment]
@dlau I'm using koa@1, please update 1.6.0.

**Comment by dlau** [comment]
Published in npm @ `1.7.0`
