### ISSUE TITLE
[Typescript] v4 ctx.request.body - Property body does not exist on type Request

### ISSUE THREAD

**Issue by xaviergonz** [dlau/koa-body#92]
## Promblem/Feature Request Summary
v4 
TS 2.9
ctx.request.body - Property body does not exist on type Request

## Environment Information

  * koa-body: 4.0.0
  * Koa: 2.x
  * Node.js: 10.3

## Current Behavior
Typescript definition is missing the body field

## Expected Behavior
It shouldn't complain about the missing type def

## Possible Solution
Adding body to the type defs

**Comment by damianb** [comment]
Also affected. Appears that the [Request augmentation](https://github.com/dlau/koa-body/blob/50d6699cfd6e85b6887dcbea5c3c845651b74af6/index.d.ts#L5) had the body typing removed [here](https://github.com/dlau/koa-body/commit/d7dd15d92478f2db6d98eb9e7e68154cc8936d76#diff-b52768974e6bc0faccb7d4b75b162c99L4)

**Comment by MarkHerhold** [comment]
released in 4.0.1

**Comment by nhhockeyplayer** [comment]
this one shut me down too

Property 'name' is missing in type '{}'.

for ctx.request.body

in my server router
