### ISSUE TITLE
files type should be any not Array<any>

### ISSUE THREAD

**Issue by gengjiawen** [dlau/koa-body#94]
From the code and debug the files is defined as a object not array
![image](https://user-images.githubusercontent.com/3759816/41197841-b0ceb37a-6c9c-11e8-8ae1-069f54bae5d4.png)

I have created pr for this: https://github.com/dlau/koa-body/pull/95.

**Comment by MarkHerhold** [comment]
How about this as a solution? Could you try this branch out?

https://github.com/dlau/koa-body/commit/ad5dd36333999191d785d16297dfc65b5e4a6b10

**Comment by gengjiawen** [comment]
I tried the fix, it works. A new release ?

**Comment by MarkHerhold** [comment]
Sure, will do it tonight. Thanks for verifying. 👍

**Comment by MarkHerhold** [comment]
4.0.2
