### ISSUE TITLE
ctx.request.body.fields  and ctx.request.body.files in koa-router.js both undefined

### ISSUE THREAD

**Issue by Chen-WeiZhen** [dlau/koa-body#96]
## Promblem/Feature Request Summary

I run `npm run examples-koa-router` and upload a picture , the terminal console log undefined from `ctx.request.body.fields` and ` ctx.request.body.files`

but the annotation is what i want , is this a bug??
## Environment Information

  * koa-body: "^7.0.1"
  * Koa: "^2.0.0"
  * Node.js: 8.11.1

## Steps to Reproduce

1.
2.
3.

**Comment by MarkHerhold** [comment]
I updated the example to be compatible with `koa-body` v3 changes. Please let me know if this answers your question.
