### ISSUE TITLE
TypeScript compiler fails because of explicit @types import

### ISSUE THREAD

**Issue by egilsster** [dlau/koa-body#98]
## Environment Information

  * koa-body: v4.0.2
  * Koa: v2.5.1
  * Node.js: v8.11.1
  * TypeScript: v2.9.1

## Current Behavior

After the new `v4.0.2` release, I started getting type errors when transpiling:

```
λ tsc --noEmit
node_modules/koa-body/index.d.ts(2,29): error TS6137: Cannot import type declaration files. Consider importing 'koa' instead of '@types/koa'.
node_modules/koa-body/index.d.ts(3,23): error TS2307: Cannot find module '@types/formidable'.
node_modules/koa-body/index.d.ts(3,23): error TS6137: Cannot import type declaration files. Consider importing 'formidable' instead of '@types/formidable'.
```

## Steps to Reproduce

1. Just have a project with TypeScript and the versions of the dependencies noted above
2. Run `tsc` / `tsc --noEmit` and see type errors

## Expected Behavior

In `v4.0.1` it compiles just fine, as expected.

## Possible Solution

Removing the `@types/*` explicit import would fix this issue.

**Comment by MarkHerhold** [comment]
Ah, sorry about this and thanks for the PR.

**Comment by MarkHerhold** [comment]
4.0.3
